-- 코드를 작성해주세요
# COALESSCE

# SELECT
#     A.ID, COUNT(B.ID) CHILD_COUNT
# FROM
#     ECOLI_DATA A
#     LEFT JOIN ECOLI_DATA B
#         ON A.ID = B.PARENT_ID
# GROUP BY
#     A.ID
# ORDER BY
#     A.ID

SELECT
    ID,
    COALESCE((SELECT COUNT(*) 
              FROM ECOLI_DATA 
              WHERE PARENT_ID = A.ID), 0) AS CHILD_COUNT
FROM
    ECOLI_DATA A
ORDER BY
    ID;