-- 코드를 작성해주세요
# NTILE, CASE, SUBQUERY_alias 지정 혹은 CTE사용(WITH)

WITH Q AS (
    SELECT
        ID, NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS QUARTILE
    FROM
        ECOLI_DATA
)


SELECT
    ID,
    CASE
        WHEN QUARTILE=1 THEN 'CRITICAL'
        WHEN QUARTILE=2 THEN 'HIGH'
        WHEN QUARTILE=3 THEN 'MEDIUM'
        WHEN QUARTILE=4 THEN 'LOW'
    END AS COLONY_NAME
FROM
    Q
ORDER BY
    ID ASC;