-- 코드를 입력하세요

SELECT
    CAR_ID, ROUND(AVG(DATEDIFF(END_DATE, START_DATE)+1),1) AS AVERAGE_DURATION
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY 
GROUP BY
    CAR_ID
HAVING 
    AVERAGE_DURATION >= 7
ORDER BY
    AVERAGE_DURATION DESC, CAR_ID DESC;
    
    
# 대여 기간을 구할 때, END_DATE와 START_DATE의 차이에 +1을 꼭 해줘야함!!!