-- 코드를 입력하세요

# 1. LEFT JOIN과 NULL 사용
# 2. NOT IN 사용

# SELECT 
#     O.ANIMAL_ID, O.NAME
# FROM 
#     ANIMAL_OUTS O 
#     LEFT JOIN ANIMAL_INS I
#     ON O.ANIMAL_ID = I.ANIMAL_ID
# WHERE 
#     I.ANIMAL_ID IS NULL
# ORDER BY 
#     O.ANIMAL_ID;
    
SELECT
    ANIMAL_ID, NAME
FROM
    ANIMAL_OUTS 
WHERE
    ANIMAL_ID NOT IN (SELECT ANIMAL_ID FROM ANIMAL_INS)
ORDER BY
    ANIMAL_ID;