-- 코드를 작성해주세요

# 마지막 ORDER BY를 TOTAL_DISTANCE로 하면 틀림.(반올림을 한 상태로 정렬하기 때문)
SELECT 
    ROUTE, 
    CONCAT(ROUND(SUM(D_BETWEEN_DIST),1),'km') TOTAL_DISTANCE, 
    CONCAT(ROUND(AVG(D_BETWEEN_DIST),2),'km') AVERAGE_DISTANCE
FROM
    SUBWAY_DISTANCE 
GROUP BY
    ROUTE
ORDER BY
    SUM(D_BETWEEN_DIST) DESC
