-- 코드를 작성해주세요

# 내 답안
SELECT
    COUNT(I.ID) FISH_COUNT, N.FISH_NAME
FROM
    FISH_INFO I LEFT JOIN FISH_NAME_INFO N ON I.FISH_TYPE=N.FISH_TYPE
GROUP BY
    N.FISH_TYPE, N.FISH_NAME
ORDER BY
    FISH_COUNT DESC

# USING을 사용하는 답안
# SELECT COUNT(TIME) AS FISH_COUNT, FISH_NAME
# FROM FISH_INFO
# JOIN FISH_NAME_INFO
# USING(FISH_TYPE)
# GROUP BY FISH_NAME
# ORDER BY FISH_COUNT DESC