-- 코드를 작성해주세요
# QUARTER
# GROUP BY가 SELECT 보다 먼저 실행 되지만, SELECT의 alias를 사용할 수 있다. 

SELECT
    CONCAT(QUARTER(DIFFERENTIATION_DATE), 'Q') QUARTER, COUNT(ID) ECOLI_COUNT
FROM
    ECOLI_DATA
GROUP BY
    QUARTER
ORDER BY
    QUARTER