-- 코드를 입력하세요
# WITH RECURSIVE

WITH RECURSIVE HOURS AS(
    SELECT 0 AS HOUR
    
    UNION ALL
    
    SELECT
        HOUR+1 AS HOUR
    FROM
        HOURS
    WHERE
        HOUR < 23
), COUNTS AS(
    SELECT
        HOUR(DATETIME) HOUR, COUNT(*) COUNT
    FROM
        ANIMAL_OUTS
    GROUP BY
        HOUR(DATETIME)
)

SELECT
    H.HOUR, IFNULL(COUNT, 0) COUNT
FROM
    HOURS H LEFT JOIN COUNTS C
    ON H.HOUR = C.HOUR