-- 코드를 작성해주세요
# 비트 연산자 & 이용
# C.GENOTYPE : 자식의 형질
# P.GENOTYPE : 부모의 형질

SELECT
    C.ID, C.GENOTYPE GENOTYPE, P.GENOTYPE PARENT_GENOTYPE
FROM
    ECOLI_DATA C
JOIN
    ECOLI_DATA P
ON 
    C.PARENT_ID = P.ID
WHERE
    C.GENOTYPE & P.GENOTYPE >= P.GENOTYPE
ORDER BY
    C.ID