-- 코드를 작성해주세요

SELECT 
    YEAR(DIFFERENTIATION_DATE) AS YEAR, B.M - A.SIZE_OF_COLONY AS YEAR_DEV, A.ID
FROM
    ECOLI_DATA AS A
    LEFT JOIN
    (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS M
    FROM ECOLI_DATA
    GROUP BY YEAR) AS B
    ON YEAR(A.DIFFERENTIATION_DATE) = B.YEAR
ORDER BY
    YEAR ASC, YEAR_DEV ASC;