-- 코드를 작성해주세요

# 나의 풀이
# SELECT 
#     YEAR(DIFFERENTIATION_DATE) AS YEAR, B.M - A.SIZE_OF_COLONY AS YEAR_DEV, A.ID
# FROM
#     ECOLI_DATA AS A
#     LEFT JOIN
#     (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS M
#     FROM ECOLI_DATA
#     GROUP BY YEAR) AS B
#     ON YEAR(A.DIFFERENTIATION_DATE) = B.YEAR
# ORDER BY
#     YEAR ASC, YEAR_DEV ASC


# 모범 답안 - WITH를 사용

WITH MAX_COLONY AS (
    SELECT 
        YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM 
        ECOLI_DATA
    GROUP BY 
        YEAR(DIFFERENTIATION_DATE)
)

SELECT 
    YEAR(E.DIFFERENTIATION_DATE) AS YEAR, M.MAX_SIZE - E.SIZE_OF_COLONY AS YEAR_DEV, E.ID
FROM 
    ECOLI_DATA AS E 
JOIN 
    MAX_COLONY AS M 
ON 
    YEAR(E.DIFFERENTIATION_DATE) = M.YEAR
ORDER BY 
    YEAR, YEAR_DEV;