-- 코드를 입력하세요
# SELECT A.FLAVOR
# FROM ICECREAM_INFO A INNER JOIN FIRST_HALF B
# ON A.FLAVOR=B.FLAVOR
# WHERE TOTAL_ORDER > 3000 AND INGREDIENT_TYPE = 'fruit_based'
# ORDER BY TOTAL_ORDER DESC;

SELECT 
    A.FLAVOR
FROM 
    ICECREAM_INFO A, FIRST_HALF B
WHERE 
    TOTAL_ORDER > 3000  
    AND INGREDIENT_TYPE = 'fruit_based'
    AND A.FLAVOR = B.FLAVOR
ORDER BY 
    TOTAL_ORDER DESC;