-- 코드를 작성해주세요
# WITH과 RANK를 사용한 풀이
# 공동 1위를 모두 추출할 수 있기에 문제의도에 더욱 적합한 풀이라고 할 수 있음
WITH R AS
(SELECT 
    EMP_NO, SUM(SCORE) AS SCORE, RANK() OVER(ORDER BY SUM(SCORE) DESC) AS RANKING
FROM
    HR_GRADE
WHERE
    YEAR = 2022
GROUP BY 
    EMP_NO)
    
    
SELECT
    R.SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM
    HR_EMPLOYEES E JOIN R ON E.EMP_NO = R.EMP_NO
WHERE
    R.RANKING = 1


# 아래는 공동 1위가 없을 때, 사용 가능한 풀이

# SELECT
#     SUM(G.SCORE) AS SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
# FROM
#     HR_EMPLOYEES E JOIN HR_GRADE G ON E.EMP_NO = G.EMP_NO
# WHERE
#     G.YEAR = 2022
# GROUP BY 
#     EMP_NO
# ORDER BY
#     SCORE DESC
# LIMIT 1