-- 코드를 입력하세요

SELECT 
    UB.TITLE, UB.BOARD_ID, REPLY_ID, UR.WRITER_ID, UR.CONTENTS, 
    DATE_FORMAT(UR.CREATED_DATE, '%Y-%m-%d') CREATED_DATE
FROM 
    USED_GOODS_BOARD UB, USED_GOODS_REPLY UR
WHERE 
    UB.BOARD_ID = UR.BOARD_ID
    AND UB.CREATED_DATE BETWEEN '2022-10-01' AND '2022-10-31'
ORDER BY 
    UR.CREATED_DATE, UB.TITLE;