-- 코드를 작성해주세요

WITH FrontEnd AS ( -- SKILLCODES FrontEnd select
    SELECT SUM(CODE) AS CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
),
C AS ( -- SKILLCODES C# select
    SELECT CODE 
    FROM SKILLCODES
    WHERE NAME = 'C#'
),
Python AS ( -- SKILLCODES Python select
    SELECT CODE FROM SKILLCODES
    WHERE NAME = 'Python'
)
SELECT 
CASE 
    WHEN D.SKILL_CODE & F.CODE >= 1 AND D.SKILL_CODE & P.CODE >= 1 THEN 'A' 
    WHEN D.SKILL_CODE & C.CODE >= 1 THEN 'B'
    WHEN D.SKILL_CODE & F.CODE >= 1 THEN 'C'
END GRADE, ID, EMAIL
FROM DEVELOPERS D, FrontEnd F, C AS C, Python P 
HAVING GRADE IS NOT NULL 
ORDER BY 1, 2